name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Endy115
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -B output
          git add .
          git commit -m "update snake" || echo "no changes"
          git push origin output --force
